version: "3.8"

services:
  mcp-search-hub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LINKUP_API_KEY=${LINKUP_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CACHE_TTL=${CACHE_TTL:-3600}
      - DEFAULT_BUDGET=${DEFAULT_BUDGET}
    restart: unless-stopped
