version: "3.8"

# Alternative development Docker Compose configuration
# Extends base configuration with aggressive development settings

include:
  - docker-compose.base.yml

services:
  mcp-search-hub:
    volumes:
      - ./:/app  # Mount local directory for live code changes
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}  # More verbose logging for development
      - CACHE_TTL=${CACHE_TTL:-60}     # Very short cache for immediate feedback
      - DEFAULT_BUDGET=${DEFAULT_BUDGET:-1.0}  # High budget for development
      - PYTHONUNBUFFERED=1  # Unbuffered output for better logging
      - MIDDLEWARE_LOGGING_INCLUDE_BODY=true  # Debug logging
      - MIDDLEWARE_ERROR_INCLUDE_TRACEBACK=true  # Full error details
    build:
      target: builder  # Use builder stage with dev tools
    command: ["python", "-m", "mcp_search_hub.main", "--transport", "streamable-http", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      interval: 5s   # Very frequent checks for development
      timeout: 3s
      start_period: 5s
      retries: 2

  redis:
    healthcheck:
      interval: 10s  # More frequent Redis checks
      timeout: 5s
      start_period: 5s