version: "3.8"

# Development Docker Compose configuration
# Extends base configuration with development-specific settings

include:
  - docker-compose.base.yml

services:
  mcp-search-hub:
    env_file: 
      - .env  # Default environment file for development
    volumes:
      - ./:/app  # Mount local directory for live code changes
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}  # More verbose logging for development
      - CACHE_TTL=${CACHE_TTL:-300}    # Shorter cache for faster iteration
      - DEFAULT_BUDGET=${DEFAULT_BUDGET:-0.5}  # Higher budget for development
      - PYTHONUNBUFFERED=1  # Unbuffered output for better logging
    build:
      target: builder  # Use builder stage for development with dev tools
    command: ["python", "-m", "mcp_search_hub.main", "--transport", "streamable-http", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      interval: 10s  # More frequent checks during development
      timeout: 5s
      start_period: 10s